import React from "react";
import { MdReport } from "react-icons/md";

const ReportTable = () => {
  const reports = [
    {
      num:'01',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-461",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "aarti mohan",
      qcStatus: "No"
    },
    {
      num:'02',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-462",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "john smith",
      qcStatus: "No"
    },
    {
      num:'03',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-463",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "john smith",
      qcStatus: "No"
    },
    {
      num:'04',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-464",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "john smith",
      qcStatus: "No"
    },
    {
      num:'05',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-465",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "john smith",
      qcStatus: "No"
    },
    {
      num:'06',
      date: "26-06-2024",
      applicationId: "GQ-MANYATA-466",
      applicantName: "Imran Umarsab Kerehittal Shek",
      status: "completed",
      generatedBy: "john smith",
      qcStatus: "No"
    }
  ];

  return (
      <div className="overflow-x-auto py-6 px-4">
      <h2 className='text-green-600 font-bold text-2xl ps-3 pb-5 flex items-center gap-4'>
        <MdReport className='text-4xl' />
        Report Summary
      </h2>
        <table className="min-w-full">
          <thead>
            <tr>
            <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">SL</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Report Date</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Application ID</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Name Of Applicant</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Overall Status</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Report Generated by</th>
              <th className="py-3 text-left px-4 border-b whitespace-nowrap uppercase">Qc Status</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report, index) => (
              <tr key={index}>
              <td className="py-3 px-4 border-b whitespace-nowrap">{report.num}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">{report.date}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">{report.applicationId}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">{report.applicantName}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">{report.status}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">{report.generatedBy}</td>
                <td className="py-3 px-4 border-b whitespace-nowrap">
                  <button className="bg-green-600 text-white py-2 px-10 rounded-md hover:bg-green-200">{report.qcStatus}</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
  );
};

export default ReportTable;
