import React, { useContext, useEffect, useMemo, useState } from 'react';
import PaginationContext from './PaginationContext';
import Pagination from './Pagination';

const ReportsList = () => {
  const { currentItem, showPerPage, setTotalResults } = useContext(PaginationContext);

    const reports =useMemo(()=>
      [
        {
          num:'01',
          date: "26-06-2024",
          applicationId: "GQ-MANYATA-461",
          applicantName: "Imran Umarsab Kerehittal Shek",
          status: "completed",
          generatedBy: "aarti mohan",
          qcStatus: "No"
        },
        {
          num:'02',
          date: "26-06-2024",
          applicationId: "GQ-MANYATA-462",
          applicantName: "Imran Umarsab Kerehittal Shek",
          status: "completed",
          generatedBy: "john smith",
          qcStatus: "No"
        },
        {
          num:'03',
          date: "26-06-2024",
          applicationId: "GQ-MANYATA-463",
          applicantName: "Imran Umarsab Kerehittal Shek",
          status: "completed",
          generatedBy: "john smith",
          qcStatus: "No"
        },
        {
          num:'04',
          date: "26-06-2024",
          applicationId: "GQ-MANYATA-464",
          applicantName: "Imran Umarsab Kerehittal Shek",
          status: "completed",
          generatedBy: "john smith",
          qcStatus: "No"
        },
        {
          num:'05',
          date: "26-06-2024",
          applicationId: "GQ-MANYATA-465",
          applicantName: "Imran Umarsab Kerehittal Shek",
          status: "completed",
          generatedBy: "john smith",
          qcStatus: "No"
        },
       
      ],[] ) ;
      const [paginatedData, setPaginatedData] = useState([]);

      useEffect(() => {
        setTotalResults(reports.length);
    
        const startIndex = (currentItem - 1) * showPerPage;
        const endIndex = startIndex + showPerPage;
        setPaginatedData(reports.slice(startIndex, endIndex));
      }, [currentItem, showPerPage, reports, setTotalResults]);
  return (
   <>
   <div className="overflow-x-auto py-4 px-4">
   <table className="min-w-full">
     <thead>
       <tr className='bg-green-500'>
       <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">SL</th>
         <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">Report Date</th>
         <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">Application ID</th>
         <th className="py-2 text-left text-white border-r px-4 border-b whitespace-nowrap uppercase">Name Of Applicant</th>
         <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">Overall Status</th>
         <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">Report Generated by</th>
         <th className="py-2 text-center text-white border-r px-4 border-b whitespace-nowrap uppercase">Qc Status</th>
       </tr>
     </thead>
     <tbody>
       {paginatedData.map((report, index) => (
         <tr key={index}>
         <td className="py-2 px-4 text-center border-l border-b border-r whitespace-nowrap">{report.num}</td>
           <td className="py-2 px-4 text-center border-b border-r whitespace-nowrap">{report.date}</td>
           <td className="py-2 px-4 text-center border-b border-r whitespace-nowrap">{report.applicationId}</td>
           <td className="py-2 px-4 text-left border-b border-r whitespace-nowrap">{report.applicantName}</td>
           <td className="py-2 px-4 text-center border-b border-r whitespace-nowrap">{report.status}</td>
           <td className="py-2 px-4 text-center border-b border-r whitespace-nowrap">{report.generatedBy}</td>
           <td className="py-2 px-4 text-center border-b border-r whitespace-nowrap">
             <button className="bg-green-600 text-white py-2 px-10 rounded-md hover:bg-green-200" >{report.qcStatus}</button>
           </td>
         </tr>
       ))}
     </tbody>
   </table>
 </div>
 <Pagination/>
   </>
  )
}

export default ReportsList